### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by PekopT** [9seconds/topographer#6]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dfbb0]

goroutine 20 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:50
github.com/9seconds/topographer/providers.(*MaxMind).Update.func1(0x0)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:45 +0x30
github.com/9seconds/topographer/providers.(*MaxMind).Update(0xc0001801e0, 0xc000058900, 0x99fa40, 0xc0002601e0)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:50 +0x5ef
github.com/9seconds/topographer/providers.(*ProviderSet).updateProvider(0xc000176ad0, 0x1, 0x91e125, 0x7, 0x0)
	/go/src/github.com/9seconds/topographer/providers/set.go:36 +0x2b2
created by github.com/9seconds/topographer/providers.(*ProviderSet).Update
	/go/src/github.com/9seconds/topographer/providers/set.go:24 +0xc5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dfbb0]

goroutine 38 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:50
github.com/9seconds/topographer/providers.(*MaxMind).Update.func1(0x0)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:45 +0x30
github.com/9seconds/topographer/providers.(*MaxMind).Update(0xc000170420, 0xc0001c2900, 0x99fa40, 0xc000248190)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:50 +0x5ef
github.com/9seconds/topographer/providers.(*ProviderSet).updateProvider(0xc000174b70, 0x1, 0x91e125, 0x7, 0x0)
	/go/src/github.com/9seconds/topographer/providers/set.go:36 +0x2b2
created by github.com/9seconds/topographer/providers.(*ProviderSet).Update
	/go/src/github.com/9seconds/topographer/providers/set.go:24 +0xc5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dfbb0]

goroutine 10 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:50
github.com/9seconds/topographer/providers.(*MaxMind).Update.func1(0x0)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:45 +0x30
github.com/9seconds/topographer/providers.(*MaxMind).Update(0xc00001e480, 0xc00005d900, 0x99fa40, 0xc000258190)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:50 +0x5ef
github.com/9seconds/topographer/providers.(*ProviderSet).updateProvider(0xc000060b60, 0x1, 0x91e125, 0x7, 0x0)
	/go/src/github.com/9seconds/topographer/providers/set.go:36 +0x2b2
created by github.com/9seconds/topographer/providers.(*ProviderSet).Update
	/go/src/github.com/9seconds/topographer/providers/set.go:24 +0xc5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dfbb0]

goroutine 7 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:50
github.com/9seconds/topographer/providers.(*MaxMind).Update.func1(0x0)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:45 +0x30
github.com/9seconds/topographer/providers.(*MaxMind).Update(0xc00001e2a0, 0xc0001ce900, 0x99fa40, 0xc00053ec80)
	/go/src/github.com/9seconds/topographer/providers/maxmind.go:50 +0x5ef
github.com/9seconds/topographer/providers.(*ProviderSet).updateProvider(0xc000060ae0, 0x1, 0x91e125, 0x7, 0x0)
	/go/src/github.com/9seconds/topographer/providers/set.go:36 +0x2b2
created by github.com/9seconds/topographer/providers.(*ProviderSet).Update
	/go/src/github.com/9seconds/topographer/providers/set.go:24 +0xc5
```

**Comment by PekopT** [comment]
@9seconds падает(

**Comment by nesc58** [comment]
Same problem here. Software77 was down.

```time="2019-01-08T15:23:42Z" level=debug msg="Access URL." url="http://software77.net/geo-ip/?DL=1"
time="2019-01-08T15:24:12Z" level=warning msg="Cannot update provider" attempt=3 error="Cannot download software77: Cannot access URL http://software77.net/geo-ip/?DL=1: Get http://software77.net/geo-ip/?DL=1: dial tcp 63.247.71.18:80: i/o timeout" provider=software77
time="2019-01-08T21:16:12Z" level=info msg="Update provider." attempt=0 provider=software77
time="2019-01-08T21:16:12Z" level=debug msg="Access URL." url="http://software77.net/geo-ip/?DL=1"
time="2019-01-08T21:16:12Z" level=debug msg="Got response." body_size=-1 code=404 url="http://software77.net/geo-ip/?DL=1"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b3400]

goroutine 129483 [running]:
os.(*File).Name(...)
        /usr/local/go/src/os/file.go:49
github.com/9seconds/topographer/providers.(*Software77).Update.func1(0x0)
        /go/src/github.com/9seconds/topographer/providers/software77.go:37 +0x30
github.com/9seconds/topographer/providers.(*Software77).Update(0xc4200a26c0, 0xc420051900, 0x945e40, 0xc420af85f0)
        /go/src/github.com/9seconds/topographer/providers/software77.go:40 +0xd3
github.com/9seconds/topographer/providers.(*ProviderSet).updateProvider(0xc420085d20, 0xc4200a2500, 0x8ef1ef, 0xa, 0x0)
        /go/src/github.com/9seconds/topographer/providers/set.go:36 +0x2cf
created by github.com/9seconds/topographer/providers.(*ProviderSet).Update
        /go/src/github.com/9seconds/topographer/providers/set.go:24 +0xc5
time="2019-01-09T08:29:30Z" level=info msg="Update provider." attempt=0 provider=software77
time="2019-01-09T08:29:30Z" level=debug msg="Access URL." url="http://software77.net/geo-ip/?DL=1"
time="2019-01-09T08:29:31Z" level=debug msg="Got response." body_size=-1 code=404 url="http://software77.net/geo-ip/?DL=1"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b3400]

goroutine 20 [running]:
os.(*File).Name(...)
        /usr/local/go/src/os/file.go:49
github.com/9seconds/topographer/providers.(*Software77).Update.func1(0x0)
        /go/src/github.com/9seconds/topographer/providers/software77.go:37 +0x30
github.com/9seconds/topographer/providers.(*Software77).Update(0xc42016a180, 0xc42004a900, 0x945e40, 0xc420174b40)
        /go/src/github.com/9seconds/topographer/providers/software77.go:40 +0xd3
github.com/9seconds/topographer/providers.(*ProviderSet).updateProvider(0xc420170cf0, 0x1, 0x8ef1ef, 0xa, 0x0)
        /go/src/github.com/9seconds/topographer/providers/set.go:36 +0x2cf
created by github.com/9seconds/topographer/providers.(*ProviderSet).Update
        /go/src/github.com/9seconds/topographer/providers/set.go:24 +0xc5
```

**Comment by 9seconds** [comment]
I hope it is closed. Sorry for inconveniences: I have a plan to rework this service because DBIP has started to provide MMDB but due to the lack of free time this still a plan.
